name: Cherry Pick

on:
  push:
    branches:
      - main


jobs:

  cherry-pick:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout active release
        - uses: actions/checkout@v2
          with:
            ref: active_release

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Attempt to create cherry pick PR
        env:
          ARROW_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          echo workspace ${{ github.workspace }}
          ls ${{ github.workspace }}
          pip3 install PyGithub
          python3 ${{ github.workspace }}/.github/actions/cherry_pick_pr.py ${{ github.event_path }}
