name: Cherry Pick

on:
  push:
    branches:
      - master


jobs:

  cherry-pick:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context);
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Beginning cherry-pick process...!'
            })
