name: Cherry Pick

on:
  push:
    branches:
      - main


jobs:

  cherry-pick:
    runs-on: ubuntu-latest
    steps:
      - name: Attempt to create cherry pick PR
        env:
          ARROW_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          pip3 install PyGithub
          python3 ${{ github.workspace }}/.github/actions/cherry_pick_pr.py ${{ github.event_path }}
