name: Cherry Pick

on:
  push:
    branches:
      - main


# basic workflow desired is on every merge to master
# (TODO)
# 1. Create a cherry pick PR with the commit to the active-release branch
# 2. Try and find the corresponding PR that was merged and add a comment to connect the two

jobs:

  cherry-pick:
    runs-on: ubuntu-latest
    steps:
      - name: Open Kimono (show env vars)
        run: |
          env
      - name: Show token
        run: |
          echo Token: ${{ github.token }}
      - name: Show event
        run: |
          cat $GITHUB_EVENT_PATH

      - name: Show python pip
        run: |
          pip freeze

      - name: Show python3 pip
        run: |
          pip3 freeze
